---
- hosts: database
  become: true
  tasks:
    - name: install multiple reqs
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - python-mysqldb
        - mysql-server

    - name: ensure mysql started
      service: name=mysql state=started enabled=yes

    - name: ensure mysql listening on all ports
      lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
                  line="bind-address = 0.0.0.0"
      notify: restart mysql

    - name: create demo database
      mysql_user: name=demo stat=present
    
    - name: create demo user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
